#!/usr/bin/perl -T

use strict;
use warnings;

use WebService::DataDog;

my $datadog = WebService::DataDog->new(
	application_key => abc123,
	api_key         => def4567890,
	verbose         => 1,
);


$datadog->send_event(
	title => $title_of_event,
	text => $text_describing_event,
	date_happened => $sometime_in_past, #optional, defaults to 'now'
	priority => $priority, #optional
	tags => $tag_list, #optional
	alert_type => $alert_type, #optional
);


my $dashboard_details = $datadog->get_dashboard(
	dashboard_id => $dashboard_id
);

my $all_dashboards = $datadog->get_all_dashboards();

my $tag_list = $datadog->get_all_tags();
my $host_tags = $datadog->get_host_tags( host => $host_id_or_name );


